name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: alokbhorunde9814
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated contribution snake"
          branch: main
